#!/usr/bin/env python3
"""Generate data/derived/mirror_clock.json — what the mirror network actually is.

Two findings, both computed from CheckFirst's aggregate data we already hold, with
no article-level access required:

1. WHAT IT PUBLISHES. The Hungarian mirror's own category counts: only ~4% of it is
   about Hungary. The rest is world filler and Russia. This turns the site's prose
   claim ("a firehose of filler") into the mirror's own bookkeeping.

2. WHOSE CLOCK IT KEEPS — A NULL RESULT, REPORTED AS ONE.
   The tempting claim is that all seven mirrors run on one central schedule: their
   hourly profiles correlate at r=0.89-0.98 in UTC. We tested it and it does not hold.

   Bare UTC correlation cannot discriminate, because five of the seven target countries
   share the same offset (+1), so re-indexing to local time barely moves them, and
   because ANY human-operated publisher shows the same day/night shape. The only pairs
   that can tell central from local timing are those with DIFFERENT offsets. For each
   such pair we find the lag that maximises correlation:

     - one central schedule   -> best lag 0
     - local audience tuning  -> best lag -1  (a UTC+2 mirror must publish an hour
                                earlier in UTC to reach the same local hour)

   Observed mean lag across the 10 cross-offset pairs is about -0.8h, i.e. closer to
   the LOCAL-tuning prediction. So we do not publish "one clock". The honest statement
   is that these mirrors show mild per-country timing adaptation, and certainly no
   evidence of a single shared publishing hour.

What none of this shows: where the operators are. A trough at 01:00-02:00 UTC is the
middle of the night in Moscow and in Budapest alike.
"""

import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw" / "pravda" / "json"
OUT = ROOT / "data" / "derived" / "mirror_clock.json"

MIRROR = "hungary.news-pravda.com"

# Standard UTC offsets of each mirror's target country. DST shifts these by an hour
# for part of the year; the profiles are aggregated over 2+ years, so both regimes are
# mixed in. That blurs the local-time test slightly — and it blurs it in the direction
# of making local alignment look WORSE, so we state it rather than lean on it.
OFFSET = {
    "hungary": 1, "slovakia": 1, "czechia": 1, "poland": 1, "deutsch": 1,
    "romania": 2, "moldova": 2,
}


def corr(a, b):
    ma, mb = statistics.mean(a), statistics.mean(b)
    num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    den = (sum((x - ma) ** 2 for x in a) * sum((y - mb) ** 2 for y in b)) ** .5
    return num / den if den else 0.0


def main() -> int:
    profiles, meta = {}, {}
    for f in sorted(RAW.glob("*_viz.json")):
        d = json.loads(f.read_text())
        key = d["domain"].split(".")[0]
        if key not in OFFSET:
            continue
        tot = d["totalArticles"]
        hours = {h["hour"]: h["count"] for h in d["publicationHours"]}
        profiles[key] = [hours.get(h, 0) / tot for h in range(24)]
        meta[key] = {"domain": d["domain"], "articles": tot,
                     "days": len(d["articlesPerDay"]),
                     "first_day": d["articlesPerDay"][0]["date"],
                     "last_day": d["articlesPerDay"][-1]["date"]}

    keys = sorted(profiles)
    # the same profiles, re-indexed to each mirror's local wall clock
    local = {k: [profiles[k][(h - OFFSET[k]) % 24] for h in range(24)] for k in keys}

    def mean_pairwise(d):
        vals = [corr(d[a], d[b]) for i, a in enumerate(keys) for b in keys[i + 1:]]
        return round(statistics.mean(vals), 4), round(min(vals), 4)

    utc_mean, utc_min = mean_pairwise(profiles)
    loc_mean, loc_min = mean_pairwise(local)

    # the discriminating test: only pairs with different UTC offsets carry information
    lags = []
    for a in keys:
        for b in keys:
            if OFFSET[a] <= OFFSET[b]:
                continue
            best = max(range(-6, 7),
                       key=lambda L: corr(profiles[a], [profiles[b][(h - L) % 24] for h in range(24)]))
            lags.append({"earlier_tz": a, "later_tz": b,
                         "offset_diff": OFFSET[a] - OFFSET[b], "best_lag_h": best})
    mean_lag = round(statistics.mean([x["best_lag_h"] for x in lags]), 3) if lags else None
    # local tuning predicts lag == -(offset difference); a shared clock predicts 0
    predicted_local = -statistics.mean([x["offset_diff"] for x in lags]) if lags else None

    hu = json.loads((RAW / f"{MIRROR}_viz.json").read_text())
    hu_total = hu["totalArticles"]

    out = {
        "note": ("Generated by scripts/derive_clock.py from CheckFirst's aggregate per-mirror "
                 "data. The clock test compares alignment in UTC against alignment in each "
                 "mirror's local time — the alternative hypothesis, not just the favoured one."),
        "categories": {
            "mirror": MIRROR,
            "total": hu_total,
            "buckets": [{"category": c["category"], "count": c["count"],
                         "share": round(c["count"] / hu_total, 4)}
                        for c in hu["categories"]],
            "about_target_share": round(
                next((c["count"] for c in hu["categories"] if c["category"] == "hungary"), 0)
                / hu_total, 4),
        },
        "clock": {
            "mirrors": [
                {"key": k, **meta[k], "utc_offset": OFFSET[k],
                 "profile_utc": [round(v, 5) for v in profiles[k]],
                 "peak_hour_utc": max(range(24), key=lambda h: profiles[k][h]),
                 "trough_hour_utc": min(range(24), key=lambda h: profiles[k][h]),
                 "peak_hour_local": (max(range(24), key=lambda h: profiles[k][h]) + OFFSET[k]) % 24,
                 "corr_with_target": round(corr(profiles[MIRROR.split('.')[0]], profiles[k]), 4)}
                for k in keys
            ],
            "test": {
                "result": "null",
                "hypothesis": "All mirrors publish on one central schedule (aligned in UTC).",
                "mean_pairwise_corr_utc": utc_mean,
                "min_pairwise_corr_utc": utc_min,
                "mean_pairwise_corr_local": loc_mean,
                "min_pairwise_corr_local": loc_min,
                "why_correlation_is_not_enough": (
                    "Five of seven target countries share UTC+1, so re-indexing to local time "
                    "barely changes those profiles; and any human-operated publisher shows the "
                    "same day/night shape. High UTC correlation is therefore expected under BOTH "
                    "hypotheses and discriminates neither."),
                "cross_offset_pairs": lags,
                "mean_best_lag_h": mean_lag,
                "predicted_lag_if_local_tuning": predicted_local,
                "predicted_lag_if_one_clock": 0,
                "reading": (
                    "The discriminating pairs sit closer to the local-tuning prediction than to a "
                    "shared clock, so we do NOT claim these mirrors run on one schedule. If "
                    "anything they show mild per-country timing adaptation. Reported as a null."),
                "does_not_show": ("Operator location. A trough at 01:00-02:00 UTC is the middle of "
                                  "the night in Moscow and Budapest alike."),
                "caveat": ("Offsets are standard time; DST moves these countries by an hour for part "
                           "of each year and the profiles aggregate 2+ years, so both regimes are "
                           "mixed in. With 10 cross-offset pairs and hour-resolution data this test "
                           "is coarse — it is strong enough to withhold a claim, not to make one."),
            },
        },
    }
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n")

    t = out["clock"]["test"]
    print(f"mirror_clock.json: {len(keys)} mirrors | UTC r={t['mean_pairwise_corr_utc']} "
          f"vs local r={t['mean_pairwise_corr_local']} (does not discriminate)")
    print(f"  discriminating test: mean best lag {t['mean_best_lag_h']:+.2f}h across "
          f"{len(t['cross_offset_pairs'])} cross-offset pairs | "
          f"one-clock predicts 0, local tuning predicts {t['predicted_lag_if_local_tuning']:+.0f}"
          f" -> RESULT: {t['result'].upper()}, no one-clock claim")
    print(f"  categories: only {out['categories']['about_target_share']*100:.1f}% of "
          f"{hu_total:,} articles are filed under 'hungary'")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
